### ISSUE TITLE
Intellisense broken in 1.3.8

### ISSUE THREAD

**Issue by t0mcat1337** [vscode-kubernetes-tools/vscode-kubernetes-tools#1070]
Hi everyone,

just realized, that in the current version 1.3.8 IntelliSense seems completely broken.

Steps to reproduce:
1) Install / Upgrade to Kubernetes extensions 1.3.8 
2) Create a new File, name "deployment.yml"
3) Start typing: De
4) Nothing happens, no suggestion is made, pressing "CTRL - Blank" gives "No suggestions":
![image](https://user-images.githubusercontent.com/3826246/167860915-313362db-4a7c-4f17-b37f-f4fbc0c1ba6a.png)

![image](https://user-images.githubusercontent.com/3826246/167861106-33c55e06-f28d-433f-a3ea-2aaa2d6948de.png)

Downgrade to 1.3.7, restart vscode:
1) Start typing: De
2) Immediatly "Kubernetes: Deployment" choice appears, pressing Enter leads to a Deployment template:

![image](https://user-images.githubusercontent.com/3826246/167861706-80608bf1-3751-4ad0-b323-5bafa8a33d67.png)

![image](https://user-images.githubusercontent.com/3826246/167861819-acd7f2d6-a7d5-4578-9bdc-34600a3abba2.png)

![image](https://user-images.githubusercontent.com/3826246/167861935-08db2959-3ff6-4fc0-8a3b-d1a5c423e8cf.png)

**Comment by lstocchi** [comment]
Hi @t0mcat1337, 

there were some users complaining about the slowness of the extension and we found out the problem was the CRDs fetching. We decided to stop fetching them automatically but to ask for user confirmation what to do https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1059. You should see a popup that asks if you want to `Enable Once`, `Disable once`, `Enable forever` or `Disable forever` the fetching.

If you never faced any issue and you want the extension to fetch CRDs everytime as before you can directly set `vs-kubernetes.crd-code-completion` to `enabled` in the settings. That should solve your issue.
Let us know. Thank you.

**Comment by lstocchi** [comment]
Hi @t0mcat1337 , thanks for opening this issue and letting us know. I was able to replicate it. Sorry for the trouble.

**Comment by pcgeek86** [comment]
I've been having the same problem here for the last week or two.

In the VSCode Extension Host logs, I am seeing this message being repeated over and over:

```
[2022-05-14 23:36:23.926] [exthost] [error] [ms-kubernetes-tools.vscode-kubernetes-tools] provider FAILED
[2022-05-14 23:36:23.928] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at C:\Users\TrevorSullivan\scoop\persist\vscode\data\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.3.8\dist\extension.js:344:75136
    at Array.filter (<anonymous>)
    at t.KubernetesCompletionProvider.filterCodeSnippets (C:\Users\TrevorSullivan\scoop\persist\vscode\data\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.3.8\dist\extension.js:344:75101)
    at t.KubernetesCompletionProvider.provideCompletionItems (C:\Users\TrevorSullivan\scoop\persist\vscode\data\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.3.8\dist\extension.js:344:74714)
    at Q.provideCompletionItems (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:111153)
    at c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:135870
    at we._withAdapter (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:126001)
    at we.$provideCompletionItems (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:135846)
    at s._doInvokeHandler (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13828)
    at s._invokeHandler (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
    at s._receiveRequest (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12121)
    at s._receiveOneMessage (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
    at c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
    at m.invoke (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at l.fire (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19001)
    at c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34426
    at m.invoke (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at l.fire (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19001)
    at r._receiveMessage (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23582)
    at c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21116
    at m.invoke (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at b.deliver (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
    at v.fire (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
    at v.acceptChunk (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15832)
    at c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14962
    at Socket.R (c:\Users\TrevorSullivan\scoop\apps\vscode\1.67.0\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```
