### ISSUE TITLE
Fails to list namespaces: Unexpected end of JSON

### ISSUE THREAD

**Issue by jhberges** [vscode-kubernetes-tools/vscode-kubernetes-tools#1326]
Type: <b>Bug</b>

May be related to local config.

- az login 
- Use Azure Kubernetes Service to import cluster to ~/.kube/config
- Select cluster as current in Kubernetes plugin
- Expand Namespaces
- Inspect extension host log and find error:

2024-09-03 15:24:14.238 [error] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at /home/jhb/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.16/dist/extension.js:32:125649
	at Generator.next (<anonymous>)
	at s (/home/jhb/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.16/dist/extension.js:32:118493)

Extension version: 1.3.16
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.8.0-41-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|23.24GB (12.79GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 55db55b4-b6dc-41e3-b976-61d1e716f6f4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by clark42** [comment]
Same issue with AWS EKS Clusters :/
